version: '2'
services:
  client:
    image: client-dev-i
    build: 
        dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
volumes:
  - node_modules: